#Created by DoomTools 2026.05.30.204802427
#Sun May 31 22:50:13 EDT 2026
path.export.lastFile=/home/william/doom/chex_micro_slaughter/dehacked_test/flemoptis.deh
path.export.source.lastFile=/home/william/doom/chex_micro_slaughter/dehacked_test/flemoptis.wad
