#Created by DoomTools 2026.05.30.204802427
#Sun May 31 22:48:39 EDT 2026
default.editor.autocomplete.autoActivationDelay=400
default.editor.autocomplete.autoActivationEnabled=false
default.editor.autocomplete.autoCompleteEnabled=true
default.editor.autocomplete.autoCompleteSingleChoices=false
default.editor.autocomplete.choicesWindowSizeHeight=200
default.editor.autocomplete.choicesWindowSizeWidth=350
default.editor.autocomplete.descriptionWindowSizeHeight=300
default.editor.autocomplete.descriptionWindowSizeWidth=450
default.editor.autocomplete.parameterDescriptionTruncateThreshold=300
default.editor.autocomplete.showDescWindow=true
default.editor.autocomplete.triggerKey=ctrl pressed SPACE
default.editor.code.animateBracketMatching=false
default.editor.code.autoIndentEnabled=true
default.editor.code.bracketMatchingEnabled=true
default.editor.code.clearWhitespaceLinesEnabled=true
default.editor.code.closeCurlyBraces=true
default.editor.code.closeMarkupTags=true
default.editor.code.codeFoldingEnabled=true
default.editor.code.eolMarkersVisible=false
default.editor.code.highlightCurrentLine=true
default.editor.code.highlightSecondaryLanguages=true
default.editor.code.hyperlinksEnabled=true
default.editor.code.linkScanningMask=128
default.editor.code.marginLineEnabled=true
default.editor.code.marginLinePosition=80
default.editor.code.markAllOnOccurrenceSearches=false
default.editor.code.markOccurrences=true
default.editor.code.markOccurrencesDelay=500
default.editor.code.paintMarkOccurrencesBorder=false
default.editor.code.paintMatchedBracketPair=true
default.editor.code.paintTabLines=true
default.editor.code.parserDelay=1000
default.editor.code.roundedSelectionEdges=false
default.editor.code.showMatchedBracketPopup=true
default.editor.code.useFocusableTips=false
default.editor.code.useSelectedTextColor=false
default.editor.code.whitespaceVisible=false
default.editor.view.encoding=UTF-8
default.editor.view.softtabs=false
default.editor.view.tabsize=4
default.editor.view.wrapping=false
default.editor.view.wrapwords=true
theme.font=Monospaced\:0\:12
theme.name=DARK
